version: '3.8'

services:
  postgres:
    image: postgres:15.8-alpine
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.1.4
    ports:
      - "5000:5000"
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://mlflow:mlflow@postgres:5432/mlflow
      MLFLOW_DEFAULT_ARTIFACT_ROOT: /mlflow/artifacts
    depends_on:
      - postgres
    volumes:
      - ./mlflow:/mlflow

  airflow:
    image: apache/airflow:2.9.1
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./deploy/airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./reports:/opt/airflow/reports
      - ./models:/opt/airflow/models
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - postgres
      - mlflow

volumes:
  postgres-db-volume: